
import Footer from "../components/home/footer"
import Header from "../components/home/header"



export default function Home() {
  return (
    <div >
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}

{/* <Layout> Home Page   </Layout> */}
      <Header/>
      <main>
      <div className="card">
          <div className="card-body">
               <h4 className="card-title" id="aboutus">About Us</h4>
               <p className="card-text"> A community making Yarl the next Silicon Valley.Yarl IT Hub (YIT) is a not for profit social enterprise which strives towards inspiring, supporting and fostering Technology, Innovation and Entrepreneurship in the community. It’s an organization by the community for the community. The Yarl IT Hub community consists of all those who share the dream of making Jaffna in to the next Silicon Valley and abides by the core values of the organization.</p>
          </div>
          </div>
          
          <div className="card">
          <div className="card-body">
               <h4 className="card-title">Our Values</h4>
               <p className="card-text">Nurture and Develop IT Talent</p>
               <p className="card-text">Empower the Community with IT</p>
               <p className="card-text">Not for profit</p>
               <p className="card-text">Innovation</p>
               <p className="card-text">Transparency</p>
               <p className="card-text">Technology and Corporate Independent</p>
               <p className="card-text">Apolitical</p>

          </div>
          </div>

          <div className="card">
          <div className="card-body">
               <h4 className="card-title">Initiatives</h4>
               <a href="#" className="card-link">Aki</a>
               <a href="#" className="card-link">Uki</a>
               <a href="#" className="card-link">YGC</a>
               <a href="#" className="card-link">Sudar</a>
               <a href="#" className="card-link">Thulir</a>
               <a href="#" className="card-link">Hatch Kalam</a>
               <a href="#" className="card-link">YGC accelerator</a>
          </div>
          </div>
          
          <div className="card">
          <div className="card-body">
               <h4 className="card-title">About Events</h4>
               <p className="card-text">There are three type of  events</p>
               <a href="#" className="card-link">UpcomingEvents</a>
               <a href="#" className="card-link">PastEvents</a>
          </div>
          </div>

          <div className="card">
          <div className="card-body">
               <h4 className="card-title">Contact Details</h4>
               <p className="card-text"> Address</p>
               <p className="card-text">Contact number</p>
               <p className="card-text">Email address</p>
          </div>
          </div>
      </main>
      <Footer/>
    </div>







  )
}
